import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-slate-900 p-4 text-center text-white mb-8">
          {/* <h1>Welcome to NextJS</h1> */}
          <Navigation />
        </header>
        {/*Here Children is the page.tsx component */}
        {children}
        <footer className="bg-slate-900 p-4 text-center text-white fixed bottom-0 left-0 w-full">
          <h1>Sparsh Jain</h1>
        </footer>
      </body>
    </html>
  );
}
